<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; }
        .container { padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 24px; }
        .details { margin-bottom: 20px; }
        .details div { margin-bottom: 10px; }
        .footer { text-align: center; margin-top: 20px; font-size: 0.8em; color: #777; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Invoice Laporan</h1>
            <p><?= date('d-m-Y', strtotime($laporan['created_at'])); ?></p>
        </div>
        <div class="details">
            <div><strong>Name:</strong> <?= htmlspecialchars($laporan['name']); ?></div>
            <div><strong>Role:</strong> <?= htmlspecialchars($laporan['role']); ?></div>
            <div><strong>Category:</strong> <?= htmlspecialchars($laporan['category']); ?></div>
            <div><strong>Amount:</strong> Rp<?= number_format($laporan['amount'], 0, ',', '.'); ?></div>
            <div><strong>Approved Amount:</strong> Rp<?= number_format($laporan['amount_approved'], 0, ',', '.'); ?></div>
            <div><strong>Type:</strong> <?= htmlspecialchars($laporan['type']); ?></div>
            <div><strong>Description:</strong> <?= htmlspecialchars($laporan['description']); ?></div>
            <div><strong>Status:</strong> <?= htmlspecialchars($laporan['status']); ?></div>
        </div>
        <div class="footer">
            <p>Generated by Sistem Pencatatan Keuangan</p>
        </div>
    </div>
</body>
</html>
